use serde::{Deserialize, Serialize};

use crate::enemies::{Enemy, EnemyProjectile, kill_enemy};
use crate::physics::PlatformerPlayerState;

// ---- Whip attack constants ----

/// Width of the whip hitbox in world units.
pub const WHIP_WIDTH: f32 = 1.5;
/// Height of the whip hitbox in world units.
pub const WHIP_HEIGHT: f32 = 0.6;
/// Horizontal offset of the whip hitbox from the player center.
pub const WHIP_OFFSET: f32 = 1.2;
/// Total duration of the attack animation.
pub const ATTACK_DURATION: f32 = 0.35;
/// Time into the attack when the hitbox becomes active.
pub const ATTACK_ACTIVE_START: f32 = 0.1;
/// Time into the attack when the hitbox deactivates.
pub const ATTACK_ACTIVE_END: f32 = 0.25;
/// Cooldown after attack completes before another can start.
pub const ATTACK_COOLDOWN: f32 = 0.15;

// ---- Damage constants ----

/// Duration of invincibility frames after taking a hit.
pub const INVINCIBILITY_DURATION: f32 = 1.5;
/// Time to wait before respawning after death.
pub const DEATH_RESPAWN_TIMER: f32 = 2.0;
/// Time penalty added to finish time per death.
pub const DEATH_TIME_PENALTY: f32 = 3.0;

/// Extended whip multiplier when WhipExtend power-up is active.
const WHIP_EXTEND_MULT: f32 = 1.8;

/// Events generated by the combat system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum CombatEvent {
    /// An enemy was killed by a player attack.
    EnemyKilled { enemy_id: u16 },
    /// A player was hit by an enemy or projectile.
    PlayerHit { player_id: u64 },
    /// A player died (HP reached 0).
    PlayerDied { player_id: u64 },
}

/// Returns true if the player's attack is in the active damage frames.
fn is_attack_active(player: &PlatformerPlayerState) -> bool {
    if player.attack_timer <= 0.0 {
        return false;
    }
    let elapsed = ATTACK_DURATION - player.attack_timer;
    (ATTACK_ACTIVE_START..=ATTACK_ACTIVE_END).contains(&elapsed)
}

/// Get the whip hitbox AABB (left, bottom, right, top) for a player.
fn whip_hitbox(player: &PlatformerPlayerState, has_whip_extend: bool) -> (f32, f32, f32, f32) {
    let mult = if has_whip_extend {
        WHIP_EXTEND_MULT
    } else {
        1.0
    };
    let width = WHIP_WIDTH * mult;
    let offset = WHIP_OFFSET * mult;
    let half_h = WHIP_HEIGHT / 2.0;

    if player.facing_right {
        let left = player.x + offset - width / 2.0;
        let right = player.x + offset + width / 2.0;
        (left, player.y - half_h, right, player.y + half_h)
    } else {
        let left = player.x - offset - width / 2.0;
        let right = player.x - offset + width / 2.0;
        (left, player.y - half_h, right, player.y + half_h)
    }
}

/// Enemy AABB: approximate as 0.8 x 0.8 centered on enemy position.
const ENEMY_HALF_SIZE: f32 = 0.4;

fn enemy_aabb(enemy: &Enemy) -> (f32, f32, f32, f32) {
    (
        enemy.x - ENEMY_HALF_SIZE,
        enemy.y - ENEMY_HALF_SIZE,
        enemy.x + ENEMY_HALF_SIZE,
        enemy.y + ENEMY_HALF_SIZE,
    )
}

/// Check if two AABBs overlap.
fn aabb_overlap(a: (f32, f32, f32, f32), b: (f32, f32, f32, f32)) -> bool {
    a.0 < b.2 && a.2 > b.0 && a.1 < b.3 && a.3 > b.1
}

/// Check a player's whip attack against all enemies. Returns combat events for kills.
pub fn check_player_attack(
    player: &PlatformerPlayerState,
    enemies: &mut [Enemy],
    has_whip_extend: bool,
) -> Vec<CombatEvent> {
    let mut events = Vec::new();

    if !is_attack_active(player) {
        return events;
    }

    let whip = whip_hitbox(player, has_whip_extend);

    for enemy in enemies.iter_mut() {
        if !enemy.alive {
            continue;
        }

        let e_aabb = enemy_aabb(enemy);
        if aabb_overlap(whip, e_aabb) {
            enemy.hp = enemy.hp.saturating_sub(1);
            if enemy.hp == 0 {
                kill_enemy(enemy);
                events.push(CombatEvent::EnemyKilled { enemy_id: enemy.id });
            }
        }
    }

    events
}

/// Player AABB for collision with enemies/projectiles.
const PLAYER_HALF_W: f32 = 0.4;
const PLAYER_HALF_H: f32 = 0.6;

fn player_aabb(player: &PlatformerPlayerState) -> (f32, f32, f32, f32) {
    (
        player.x - PLAYER_HALF_W,
        player.y - PLAYER_HALF_H,
        player.x + PLAYER_HALF_W,
        player.y + PLAYER_HALF_H,
    )
}

/// Projectile AABB: small 0.3 x 0.3 hitbox.
const PROJ_HALF_SIZE: f32 = 0.15;

fn projectile_aabb(proj: &EnemyProjectile) -> (f32, f32, f32, f32) {
    (
        proj.x - PROJ_HALF_SIZE,
        proj.y - PROJ_HALF_SIZE,
        proj.x + PROJ_HALF_SIZE,
        proj.y + PROJ_HALF_SIZE,
    )
}

/// Check if enemies or projectiles hit a player. Applies damage if not invincible.
/// Returns combat events for hits/deaths.
pub fn check_enemy_damage(
    player: &mut PlatformerPlayerState,
    player_id: u64,
    enemies: &[Enemy],
    projectiles: &[EnemyProjectile],
    has_invincibility: bool,
) -> Vec<CombatEvent> {
    let mut events = Vec::new();

    // Skip if player is dead, invincible, or in respawn
    if player.death_respawn_timer > 0.0 || player.invincibility_timer > 0.0 || has_invincibility {
        return events;
    }

    let p_aabb = player_aabb(player);

    // Check enemy body collisions
    for enemy in enemies {
        if !enemy.alive {
            continue;
        }
        let e_aabb = enemy_aabb(enemy);
        if aabb_overlap(p_aabb, e_aabb) {
            events.extend(apply_damage(player, player_id));
            return events; // Only one hit per tick
        }
    }

    // Check projectile collisions
    for proj in projectiles {
        let proj_box = projectile_aabb(proj);
        if aabb_overlap(p_aabb, proj_box) {
            events.extend(apply_damage(player, player_id));
            return events; // Only one hit per tick
        }
    }

    events
}

/// Apply damage to a player: reduce HP, start invincibility, handle death.
pub fn apply_damage(player: &mut PlatformerPlayerState, player_id: u64) -> Vec<CombatEvent> {
    let mut events = Vec::new();

    player.hp = player.hp.saturating_sub(1);
    events.push(CombatEvent::PlayerHit { player_id });

    if player.hp == 0 {
        // Player died
        player.death_respawn_timer = DEATH_RESPAWN_TIMER;
        player.deaths += 1;
        player.vx = 0.0;
        player.vy = 0.0;
        events.push(CombatEvent::PlayerDied { player_id });
    } else {
        // Just hurt, grant invincibility frames
        player.invincibility_timer = INVINCIBILITY_DURATION;
    }

    events
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::physics::AnimState;

    fn make_test_player() -> PlatformerPlayerState {
        PlatformerPlayerState::new(5.0, 5.0)
    }

    fn make_test_enemy(id: u16, x: f32, y: f32) -> Enemy {
        Enemy {
            id,
            enemy_type: crate::enemies::EnemyType::Skeleton,
            x,
            y,
            vx: 0.0,
            vy: 0.0,
            hp: 1,
            patrol_min_x: x - 2.0,
            patrol_max_x: x + 2.0,
            alive: true,
            respawn_timer: 0.0,
            facing_right: true,
            anim_time: 0.0,
            shoot_timer: 0.0,
        }
    }

    #[test]
    fn attack_not_active_when_timer_zero() {
        let player = make_test_player();
        assert!(!is_attack_active(&player));
    }

    #[test]
    fn attack_active_during_correct_frames() {
        let mut player = make_test_player();
        // Set attack_timer so that elapsed is within active window
        // elapsed = ATTACK_DURATION - attack_timer
        // We want ATTACK_ACTIVE_START <= elapsed <= ATTACK_ACTIVE_END
        // So attack_timer = ATTACK_DURATION - 0.15 (middle of active window)
        player.attack_timer = ATTACK_DURATION - 0.15;
        assert!(is_attack_active(&player));
    }

    #[test]
    fn attack_not_active_before_start() {
        let mut player = make_test_player();
        // elapsed = ATTACK_DURATION - attack_timer
        // We want elapsed < ATTACK_ACTIVE_START (0.1)
        // So attack_timer > ATTACK_DURATION - 0.1 = 0.25
        player.attack_timer = 0.30;
        assert!(!is_attack_active(&player));
    }

    #[test]
    fn whip_hitbox_facing_right() {
        let mut player = make_test_player();
        player.facing_right = true;
        let (left, bottom, right, top) = whip_hitbox(&player, false);
        // Hitbox should be to the right of the player
        assert!(left > player.x, "Whip should be to the right");
        assert!(right > left, "Right should be > left");
        assert!(top > bottom, "Top should be > bottom");
    }

    #[test]
    fn whip_hitbox_facing_left() {
        let mut player = make_test_player();
        player.facing_right = false;
        let (_left, _bottom, right, _top) = whip_hitbox(&player, false);
        // Hitbox should be to the left of the player
        assert!(right < player.x, "Whip should be to the left");
    }

    #[test]
    fn whip_extend_increases_range() {
        let player = make_test_player();
        let (l1, _, r1, _) = whip_hitbox(&player, false);
        let (l2, _, r2, _) = whip_hitbox(&player, true);
        let normal_width = r1 - l1;
        let extended_width = r2 - l2;
        assert!(
            extended_width > normal_width,
            "Extended whip should be wider: {} vs {}",
            extended_width,
            normal_width,
        );
    }

    #[test]
    fn check_player_attack_hits_enemy() {
        let mut player = make_test_player();
        player.facing_right = true;
        // Set attack to active frames
        player.attack_timer = ATTACK_DURATION - 0.15;

        // Place enemy within whip range (to the right)
        let mut enemies = vec![make_test_enemy(0, player.x + WHIP_OFFSET, player.y)];

        let events = check_player_attack(&player, &mut enemies, false);

        assert!(!events.is_empty(), "Should have killed the enemy");
        assert!(
            matches!(events[0], CombatEvent::EnemyKilled { enemy_id: 0 }),
            "Should be EnemyKilled event"
        );
        assert!(!enemies[0].alive, "Enemy should be dead");
    }

    #[test]
    fn check_player_attack_misses_distant_enemy() {
        let mut player = make_test_player();
        player.facing_right = true;
        player.attack_timer = ATTACK_DURATION - 0.15;

        // Place enemy far away
        let mut enemies = vec![make_test_enemy(0, player.x + 10.0, player.y)];

        let events = check_player_attack(&player, &mut enemies, false);

        assert!(events.is_empty(), "Should not hit distant enemy");
        assert!(enemies[0].alive, "Distant enemy should still be alive");
    }

    #[test]
    fn check_enemy_damage_hits_player() {
        let mut player = make_test_player();
        let enemies = vec![make_test_enemy(0, player.x, player.y)];
        let projectiles = Vec::new();

        let events = check_enemy_damage(&mut player, 1, &enemies, &projectiles, false);

        assert!(!events.is_empty(), "Player should be hit");
        assert!(
            matches!(events[0], CombatEvent::PlayerHit { player_id: 1 }),
            "Should be PlayerHit event"
        );
        assert_eq!(player.hp, 2, "HP should decrease from 3 to 2");
        assert!(
            player.invincibility_timer > 0.0,
            "Should have invincibility frames"
        );
    }

    #[test]
    fn check_enemy_damage_skips_invincible() {
        let mut player = make_test_player();
        player.invincibility_timer = 1.0; // Already invincible
        let enemies = vec![make_test_enemy(0, player.x, player.y)];
        let projectiles = Vec::new();

        let events = check_enemy_damage(&mut player, 1, &enemies, &projectiles, false);

        assert!(events.is_empty(), "Invincible player should not be hit");
        assert_eq!(player.hp, 3, "HP should not change");
    }

    #[test]
    fn check_enemy_damage_skips_with_powerup_invincibility() {
        let mut player = make_test_player();
        let enemies = vec![make_test_enemy(0, player.x, player.y)];
        let projectiles = Vec::new();

        let events = check_enemy_damage(&mut player, 1, &enemies, &projectiles, true);

        assert!(
            events.is_empty(),
            "Player with Invincibility powerup should not be hit"
        );
    }

    #[test]
    fn player_death_on_zero_hp() {
        let mut player = make_test_player();
        player.hp = 1; // One hit from death
        let enemies = vec![make_test_enemy(0, player.x, player.y)];
        let projectiles = Vec::new();

        let events = check_enemy_damage(&mut player, 1, &enemies, &projectiles, false);

        assert_eq!(events.len(), 2, "Should have PlayerHit and PlayerDied");
        assert!(
            events
                .iter()
                .any(|e| matches!(e, CombatEvent::PlayerDied { .. })),
            "Should have PlayerDied event"
        );
        assert_eq!(player.hp, 0, "HP should be 0");
        assert!(
            player.death_respawn_timer > 0.0,
            "Should have respawn timer"
        );
        assert_eq!(player.deaths, 1, "Death count should increment");
    }

    #[test]
    fn projectile_hits_player() {
        let mut player = make_test_player();
        let enemies = Vec::new();
        let projectiles = vec![EnemyProjectile {
            x: player.x,
            y: player.y,
            vx: 0.0,
            vy: 0.0,
            lifetime: 2.0,
        }];

        let events = check_enemy_damage(&mut player, 1, &enemies, &projectiles, false);

        assert!(!events.is_empty(), "Projectile should hit player");
        assert_eq!(player.hp, 2, "HP should decrease from 3 to 2");
    }

    #[test]
    fn dead_enemy_not_considered_for_damage() {
        let mut player = make_test_player();
        let mut enemy = make_test_enemy(0, player.x, player.y);
        enemy.alive = false;
        let enemies = vec![enemy];
        let projectiles = Vec::new();

        let events = check_enemy_damage(&mut player, 1, &enemies, &projectiles, false);

        assert!(events.is_empty(), "Dead enemy should not damage player");
        assert_eq!(player.hp, 3, "HP should not change");
    }

    #[test]
    fn aabb_overlap_works_correctly() {
        // Overlapping
        assert!(aabb_overlap((0.0, 0.0, 2.0, 2.0), (1.0, 1.0, 3.0, 3.0)));
        // Not overlapping
        assert!(!aabb_overlap((0.0, 0.0, 1.0, 1.0), (2.0, 2.0, 3.0, 3.0)));
        // Touching edges (not overlapping)
        assert!(!aabb_overlap((0.0, 0.0, 1.0, 1.0), (1.0, 0.0, 2.0, 1.0)));
    }

    // Suppress dead code warning for AnimState import used in test setup
    #[allow(unused)]
    fn _use_anim_state() -> AnimState {
        AnimState::Idle
    }
}
